<section class="page-section admin-page"><div class="container-fluid px-lg-5">
<div class="section-title"><div><p class="eyebrow">VẬN HÀNH</p><h1>Quản trị Home2Home</h1><p>Quản lý dữ liệu với lịch sử thao tác có thể truy vết.</p></div></div>
<div class="stat-grid"><div><span>Người dùng</span><strong><?= (int)$stats['users'] ?></strong></div><div><span>Host</span><strong><?= (int)$stats['hosts'] ?></strong></div><div><span>Chỗ ở</span><strong><?= (int)$stats['listings'] ?></strong></div><div><span>Booking</span><strong><?= (int)$stats['bookings'] ?></strong></div><div><span>Doanh thu hoàn thành</span><strong><?= number_format((float)$stats['revenue'],0,',','.') ?>đ</strong></div></div>

<section class="surface-card mt-4"><h2>Tạo tài khoản</h2><form class="form-row" method="post" action="<?= e(url('/admin/users')) ?>"><?= csrf_field() ?><div class="col-md-3 mb-2"><input class="form-control" name="full_name" placeholder="Họ tên" required></div><div class="col-md-3 mb-2"><input class="form-control" type="email" name="email" placeholder="Email" required></div><div class="col-md-2 mb-2"><input class="form-control" name="phone" placeholder="Số điện thoại"></div><div class="col-md-2 mb-2"><input class="form-control" type="password" name="password" minlength="8" placeholder="Mật khẩu" required></div><div class="col-md-2 mb-2"><input type="hidden" name="roles[]" value="guest"><button class="btn btn-primary btn-block">Tạo Guest</button></div></form></section>

<section class="surface-card mt-4"><div class="section-title compact"><h2>Người dùng</h2><form class="form-inline"><input class="form-control mr-2" name="q" value="<?= e($_GET['q']??'') ?>" placeholder="Tìm email hoặc họ tên"><button class="btn btn-outline-primary">Tìm</button></form></div><div class="table-responsive"><table class="table"><thead><tr><th>Tài khoản</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
<?php foreach($users as $user): ?><tr><td><strong><?= e($user['full_name']) ?></strong><br><small><?= e($user['email']) ?></small></td><td><form class="inline-role-form" method="post" action="<?= e(url('/admin/users/'.$user['id'].'/roles')) ?>"><?= csrf_field() ?><?php foreach(['guest','host','admin'] as $role): ?><label><input type="checkbox" name="roles[]" value="<?= $role ?>" <?= in_array($role,explode(',',$user['roles']??''),true)?'checked':'' ?>> <?= $role ?></label><?php endforeach; ?><button class="btn btn-sm btn-ghost">Lưu</button></form></td><td><span class="status status-<?= e($user['status']) ?>"><?= e($user['status']) ?></span></td><td><div class="action-row"><form method="post" action="<?= e(url('/admin/users/'.$user['id'].'/status')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $user['status']==='active'?'suspended':'active' ?>"><button class="btn btn-sm <?= $user['status']==='active'?'btn-outline-danger':'btn-primary' ?>"><?= $user['status']==='active'?'Khóa':'Mở khóa' ?></button></form><form method="post" action="<?= e(url('/admin/users/'.$user['id'].'/delete')) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger" data-confirm="Xóa mềm tài khoản này?">Xóa</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="surface-card mt-4"><h2>Chỉnh sửa hồ sơ người dùng</h2><p class="text-muted">Cập nhật thông tin chi tiết mà không cần thay đổi vai trò hoặc trạng thái.</p><div class="action-row"><?php foreach($users as $user): ?><a class="btn btn-sm btn-outline-primary" href="<?= e(url('/admin/users/'.$user['id'].'/edit')) ?>"><?= e($user['full_name']) ?></a><?php endforeach; ?></div></section>

<section class="surface-card mt-4"><h2>Kiểm duyệt chỗ ở</h2><div class="table-responsive"><table class="table"><thead><tr><th>Tin đăng</th><th>Host</th><th>Trạng thái</th><th>Quyết định</th><th>Quản lý</th></tr></thead><tbody>
<?php foreach($listings as $listing): ?><tr><td><strong><?= e($listing['title']) ?></strong><br><small><?= e($listing['city']) ?> · <?= e($listing['property_type']) ?></small></td><td><?= e($listing['host_name']) ?></td><td><span class="status status-<?= e($listing['moderation_status']) ?>"><?= e($listing['moderation_status']) ?></span><?php if($listing['moderation_note']): ?><br><small><?= e($listing['moderation_note']) ?></small><?php endif; ?></td><td><form class="moderation-form" method="post" action="<?= e(url('/admin/listings/'.$listing['id'].'/moderate')) ?>"><?= csrf_field() ?><input class="form-control form-control-sm" name="note" placeholder="Lý do / ghi chú"><button class="btn btn-sm btn-primary" name="action" value="approved">Duyệt</button><button class="btn btn-sm btn-outline-danger" name="action" value="rejected">Từ chối</button></form></td><td><div class="action-row"><a class="btn btn-sm btn-outline-primary" href="<?= e(url('/admin/listings/'.$listing['id'].'/edit')) ?>">Sửa</a><form method="post" action="<?= e(url('/admin/listings/'.$listing['id'].'/visibility')) ?>"><?= csrf_field() ?><input type="hidden" name="visible" value="<?= $listing['is_visible']?0:1 ?>"><button class="btn btn-sm btn-ghost"><?= $listing['is_visible']?'Ẩn':'Hiện' ?></button></form><form method="post" action="<?= e(url('/admin/listings/'.$listing['id'].'/delete')) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger" data-confirm="Gỡ listing này?">Gỡ</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="surface-card mt-4"><h2>Booking toàn hệ thống</h2><div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>Chỗ ở</th><th>Guest / Host</th><th>Ngày</th><th>Trạng thái</th><th>Tổng / thao tác</th></tr></thead><tbody>
<?php foreach($bookings as $booking): ?><tr><td>#<?= (int)$booking['id'] ?></td><td><?= e($booking['title']) ?></td><td><?= e($booking['guest_name']) ?> / <?= e($booking['host_name']) ?></td><td><?= e($booking['check_in']) ?> → <?= e($booking['check_out']) ?></td><td><span class="status status-<?= e($booking['status']) ?>"><?= e($booking['status']) ?></span></td><td><?= number_format((float)$booking['total_amount'],0,',','.') ?>đ<?php if($booking['status']==='pending'): ?><div class="action-row"><form method="post" action="<?= e(url('/admin/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="confirmed"><button class="btn btn-sm btn-primary">Xác nhận</button></form><form method="post" action="<?= e(url('/admin/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="rejected"><button class="btn btn-sm btn-outline-danger">Từ chối</button></form></div><?php elseif($booking['status']==='confirmed'&&$booking['check_out']<=date('Y-m-d')): ?><form class="mt-2" method="post" action="<?= e(url('/admin/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="completed"><button class="btn btn-sm btn-primary">Hoàn thành</button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
</div></section>
