<section class="page-section admin-page"><div class="container-fluid px-lg-5">
<div class="section-title"><div><p class="eyebrow">VẬN HÀNH</p><h1>Quản trị Home2Home</h1><div class="action-row"><a class="btn btn-ghost" href="<?= e(url('/admin/catalog')) ?>">Danh mục</a><a class="btn btn-ghost" href="<?= e(url('/admin/reviews')) ?>">Đánh giá</a><a class="btn btn-ghost" href="<?= e(url('/admin/reports')) ?>">Báo cáo</a></div><p>Quản lý dữ liệu với lịch sử thao tác có thể truy vết.</p></div></div>
<div class="stat-grid"><div><span>Người dùng</span><strong><?= (int)$stats['users'] ?></strong></div><div><span>Guest</span><strong><?= (int)$stats['guests'] ?></strong></div><div><span>Host</span><strong><?= (int)$stats['hosts'] ?></strong></div><div><span>Chỗ ở</span><strong><?= (int)$stats['listings'] ?></strong></div><div><span>Booking</span><strong><?= (int)$stats['bookings'] ?></strong></div><div><span>Doanh thu hoàn thành</span><strong><?= number_format((float)$stats['revenue'],0,',','.') ?>đ</strong></div></div>

<section class="surface-card mt-4"><h2>Tạo tài khoản</h2><form class="form-row" method="post" action="<?= e(url('/admin/users')) ?>"><?= csrf_field() ?><div class="form-group col-md-3"><label for="admin-create-name">Họ tên</label><input class="form-control" id="admin-create-name" name="full_name" placeholder="Họ tên" required></div><div class="form-group col-md-3"><label for="admin-create-email">Email</label><input class="form-control" id="admin-create-email" type="email" name="email" placeholder="Email" required></div><div class="form-group col-md-2"><label for="admin-create-phone">Số điện thoại</label><input class="form-control" id="admin-create-phone" name="phone" placeholder="Số điện thoại"></div><div class="form-group col-md-2"><label for="admin-create-password">Mật khẩu</label><input class="form-control" id="admin-create-password" type="password" name="password" minlength="8" placeholder="Mật khẩu" autocomplete="new-password" required></div><div class="form-group col-md-2 align-self-end"><input type="hidden" name="roles[]" value="guest"><button class="btn btn-primary btn-block">Tạo Guest</button></div></form></section>

<section class="surface-card mt-4"><div class="section-title compact"><h2>Người dùng</h2><form class="form-inline"><label class="sr-only" for="admin-user-search">Tìm email hoặc họ tên</label><input class="form-control mr-2" id="admin-user-search" name="q" value="<?= e($_GET['q']??'') ?>" placeholder="Tìm email hoặc họ tên"><button class="btn btn-outline-primary">Tìm</button></form></div><div class="table-responsive" tabindex="0" role="region" aria-label="Danh sách người dùng"><table class="table"><thead><tr><th>Tài khoản</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
<?php foreach($users as $user): ?><tr><td><strong><?= e($user['full_name']) ?></strong><br><small><?= e($user['email']) ?></small></td><td><form class="inline-role-form" method="post" action="<?= e(url('/admin/users/'.$user['id'].'/roles')) ?>"><?= csrf_field() ?><?php foreach(['guest','host','admin'] as $role): ?><label><input type="checkbox" name="roles[]" value="<?= $role ?>" <?= in_array($role,explode(',',$user['roles']??''),true)?'checked':'' ?>> <?= $role ?></label><?php endforeach; ?><button class="btn btn-sm btn-ghost">Lưu</button></form></td><td><span class="status status-<?= e($user['status']) ?>"><?= e($user['status']) ?></span></td><td><div class="action-row"><form method="post" action="<?= e(url('/admin/users/'.$user['id'].'/status')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $user['status']==='active'?'suspended':'active' ?>"><button class="btn btn-sm <?= $user['status']==='active'?'btn-outline-danger':'btn-primary' ?>"><?= $user['status']==='active'?'Khóa':'Mở khóa' ?></button></form><form method="post" action="<?= e(url('/admin/users/'.$user['id'].'/delete')) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger" data-confirm="Xóa mềm tài khoản này?">Xóa</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="surface-card mt-4"><h2>Chỉnh sửa hồ sơ người dùng</h2><p class="text-muted">Cập nhật thông tin chi tiết mà không cần thay đổi vai trò hoặc trạng thái.</p><div class="action-row"><?php foreach($users as $user): ?><a class="btn btn-sm btn-outline-primary" href="<?= e(url('/admin/users/'.$user['id'].'/edit')) ?>"><?= e($user['full_name']) ?></a><?php endforeach; ?></div></section>

<section class="surface-card mt-4"><h2>Kiểm duyệt chỗ ở</h2><div class="table-responsive" tabindex="0" role="region" aria-label="Danh sách tin đăng"><table class="table"><thead><tr><th>Tin đăng</th><th>Host</th><th>Trạng thái</th><th>Quyết định</th><th>Quản lý</th></tr></thead><tbody>
<?php foreach($listings as $listing): ?><tr><td><strong><?= e($listing['title']) ?></strong><br><small><?= e($listing['city']) ?> · <?= e($listing['property_type']) ?></small></td><td><?= e($listing['host_name']) ?></td><td><span class="status status-<?= e($listing['moderation_status']) ?>"><?= e($listing['moderation_status']) ?></span><?php if($listing['moderation_note']): ?><br><small><?= e($listing['moderation_note']) ?></small><?php endif; ?></td><td><form class="moderation-form" method="post" action="<?= e(url('/admin/listings/'.$listing['id'].'/moderate')) ?>"><?= csrf_field() ?><label class="sr-only" for="moderation-note-<?= (int)$listing['id'] ?>">Lý do / ghi chú cho <?= e($listing['title']) ?></label><input class="form-control form-control-sm" id="moderation-note-<?= (int)$listing['id'] ?>" name="note" placeholder="Lý do / ghi chú"><button class="btn btn-sm btn-primary" name="action" value="approved">Duyệt</button><button class="btn btn-sm btn-outline-danger" name="action" value="rejected">Từ chối</button></form></td><td><div class="action-row"><a class="btn btn-sm btn-ghost" href="<?= e(url('/admin/listings/'.$listing['id'].'/preview')) ?>">Xem trước</a><a class="btn btn-sm btn-outline-primary" href="<?= e(url('/admin/listings/'.$listing['id'].'/edit')) ?>">Sửa</a><form method="post" action="<?= e(url('/admin/listings/'.$listing['id'].'/visibility')) ?>"><?= csrf_field() ?><input type="hidden" name="visible" value="<?= $listing['is_visible']?0:1 ?>"><button class="btn btn-sm btn-ghost"><?= $listing['is_visible']?'Ẩn':'Hiện' ?></button></form><form method="post" action="<?= e(url('/admin/listings/'.$listing['id'].'/delete')) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger" data-confirm="Gỡ listing này?">Gỡ</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<section class="surface-card mt-4"><h2>Booking toàn hệ thống</h2><form class="form-row mb-3" method="get" action="<?= e(url('/admin')) ?>"><div class="form-group col-md-7"><label for="booking-query">ID, tên tin, Guest hoặc Host</label><input class="form-control" id="booking-query" name="booking_q" maxlength="254" value="<?= e($bookingQuery) ?>"></div><div class="form-group col-md-3"><label for="booking-status">Trạng thái</label><select class="form-control" id="booking-status" name="booking_status"><?php foreach([''=>'Tất cả','pending'=>'Chờ duyệt','confirmed'=>'Đã xác nhận','rejected'=>'Bị từ chối','cancelled'=>'Đã hủy','completed'=>'Hoàn thành'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= $bookingStatus===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="col-md-2 align-self-end form-group"><button class="btn btn-primary btn-block">Tra cứu</button></div></form><?php if(!$bookings): ?><p class="text-muted">Không có booking khớp bộ lọc.</p><?php endif; ?><div class="table-responsive" tabindex="0" role="region" aria-label="Danh sách booking"><table class="table"><thead><tr><th>ID</th><th>Chỗ ở</th><th>Guest / Host</th><th>Ngày</th><th>Trạng thái</th><th>Tổng / thao tác</th></tr></thead><tbody>
<?php foreach($bookings as $booking): ?><tr><td><a href="<?= e(url('/bookings/'.$booking['id'])) ?>">#<?= (int)$booking['id'] ?> · Chi tiết</a></td><td><?= e($booking['title']) ?></td><td><?= e($booking['guest_name']) ?> / <?= e($booking['host_name']) ?></td><td><?= e($booking['check_in']) ?> → <?= e($booking['check_out']) ?></td><td><span class="status status-<?= e($booking['status']) ?>"><?= e($booking['status']) ?></span></td><td><?= number_format((float)$booking['total_amount'],0,',','.') ?>đ<?php if($booking['status']==='pending'): ?><div class="action-row"><form method="post" action="<?= e(url('/admin/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="confirmed"><button class="btn btn-sm btn-primary">Xác nhận</button></form><form method="post" action="<?= e(url('/admin/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="rejected"><button class="btn btn-sm btn-outline-danger">Từ chối</button></form></div><?php elseif($booking['status']==='confirmed'&&$booking['check_out']<=date('Y-m-d')): ?><form class="mt-2" method="post" action="<?= e(url('/admin/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="completed"><button class="btn btn-sm btn-primary">Hoàn thành</button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
</div></section>
