<section class="page-section"><div class="container">
<div class="section-title"><div><p class="eyebrow">KHÔNG GIAN HOST</p><h1>Quản lý chỗ ở</h1><p>Theo dõi tin đăng, lịch trống và yêu cầu đặt chỗ từ một nơi.</p></div><a class="btn btn-primary" href="<?= e(url('/host/listings/create')) ?>">+ Đăng chỗ ở</a></div>
<div class="stat-grid"><div><span>Chỗ ở</span><strong><?= (int)$stats['listings'] ?></strong></div><div><span>Booking</span><strong><?= (int)$stats['bookings'] ?></strong></div><div><span>Hoàn thành</span><strong><?= (int)$stats['completed'] ?></strong></div><div><span>Doanh thu</span><strong><?= number_format((float)$stats['revenue'],0,',','.') ?>đ</strong></div></div>
<section class="surface-card mt-4"><h2>Tin đăng của bạn</h2><?php if(!$listings): ?><div class="empty-state"><h3>Chưa có chỗ ở</h3><p>Hãy tạo tin đầu tiên để bắt đầu nhận booking.</p><a class="btn btn-primary" href="<?= e(url('/host/listings/create')) ?>">Đăng chỗ ở</a></div><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Chỗ ở</th><th>Trạng thái</th><th>Hiển thị</th><th>Quản lý</th></tr></thead><tbody>
<?php foreach($listings as $listing): ?><tr><td><strong><?= e($listing['title']) ?></strong><br><small><?= e($listing['city']) ?></small></td><td><span class="status status-<?= e($listing['moderation_status']) ?>"><?= e($listing['moderation_status']) ?></span></td><td><form method="post" action="<?= e(url('/host/listings/'.$listing['id'].'/visibility')) ?>"><?= csrf_field() ?><input type="hidden" name="visible" value="<?= $listing['is_visible']?0:1 ?>"><button class="btn btn-sm btn-ghost"><?= $listing['is_visible']?'Ẩn':'Hiện' ?></button></form></td><td><div class="action-row"><a class="btn btn-sm btn-outline-primary" href="<?= e(url('/host/listings/'.$listing['id'].'/edit')) ?>">Chỉnh sửa</a><a class="btn btn-sm btn-ghost" href="<?= e(url('/host/listings/'.$listing['id'].'/availability')) ?>">Lịch khả dụng</a><?php if($listing['moderation_status']==='approved'&&$listing['is_visible']): ?><a class="btn btn-sm btn-ghost" href="<?= e(url('/listings/'.$listing['id'])) ?>">Xem tin</a><?php endif; ?></div></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></section>
<section class="surface-card mt-4"><h2>Yêu cầu đặt chỗ</h2><?php if(!$bookings): ?><div class="empty-state"><h3>Chưa có yêu cầu đặt chỗ</h3><p>Booking mới sẽ xuất hiện tại đây.</p></div><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Khách</th><th>Chỗ ở</th><th>Ngày</th><th>Tổng</th><th>Trạng thái / hành động</th></tr></thead><tbody>
<?php foreach($bookings as $booking): ?><tr><td><?= e($booking['guest_name']) ?><br><small><?= e($booking['guest_phone']) ?></small></td><td><?= e($booking['title']) ?></td><td><?= e($booking['check_in']) ?> → <?= e($booking['check_out']) ?></td><td><?= number_format((float)$booking['total_amount'],0,',','.') ?>đ</td><td><span class="status status-<?= e($booking['status']) ?>"><?= e($booking['status']) ?></span><?php if($booking['status']==='pending'): ?><div class="action-row"><form method="post" action="<?= e(url('/host/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="confirmed"><button class="btn btn-sm btn-primary">Chấp nhận</button></form><form method="post" action="<?= e(url('/host/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="rejected"><button class="btn btn-sm btn-outline-danger">Từ chối</button></form></div><?php elseif($booking['status']==='confirmed'&&$booking['check_out']<=date('Y-m-d')): ?><form method="post" action="<?= e(url('/host/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="completed"><button class="btn btn-sm btn-primary">Hoàn thành</button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></section>
</div></section>
