<section class="page-section"><div class="container">
<div class="section-title"><div><p class="eyebrow">KHÔNG GIAN HOST</p><h1>Quản lý chỗ ở</h1><a href="<?= e(url('/host/reviews')) ?>">Đánh giá của khách</a><p>Theo dõi tin đăng, lịch trống và yêu cầu đặt chỗ từ một nơi.</p></div><a class="btn btn-primary" href="<?= e(url('/host/listings/create')) ?>">+ Đăng chỗ ở</a></div>
<div class="stat-grid"><div><span>Chỗ ở</span><strong><?= (int)$stats['listings'] ?></strong></div><div><span>Booking</span><strong><?= (int)$stats['bookings'] ?></strong></div><div><span>Hoàn thành</span><strong><?= (int)$stats['completed'] ?></strong></div><div><span>Doanh thu</span><strong><?= number_format((float)$stats['revenue'],0,',','.') ?>đ</strong></div></div>
<section class="surface-card mt-4"><h2>Tin đăng của bạn</h2><?php if(!$listings): ?><div class="empty-state"><h3>Chưa có chỗ ở</h3><p>Hãy tạo tin đầu tiên để bắt đầu nhận booking.</p><a class="btn btn-primary" href="<?= e(url('/host/listings/create')) ?>">Đăng chỗ ở</a></div><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Chỗ ở</th><th>Trạng thái</th><th>Hiển thị</th><th>Quản lý</th></tr></thead><tbody>
<?php foreach($listings as $listing): ?><tr><td><strong><?= e($listing['title']) ?></strong><br><small><?= e($listing['city']) ?></small></td><td><span class="status status-<?= e($listing['moderation_status']) ?>"><?= e($listing['moderation_status']) ?></span></td><td><form method="post" action="<?= e(url('/host/listings/'.$listing['id'].'/visibility')) ?>"><?= csrf_field() ?><input type="hidden" name="visible" value="<?= $listing['is_visible']?0:1 ?>"><button class="btn btn-sm btn-ghost"><?= $listing['is_visible']?'Ẩn':'Hiện' ?></button></form></td><td><div class="action-row"><a class="btn btn-sm btn-outline-primary" href="<?= e(url('/host/listings/'.$listing['id'].'/edit')) ?>">Chỉnh sửa</a><a class="btn btn-sm btn-ghost" href="<?= e(url('/host/listings/'.$listing['id'].'/availability')) ?>">Lịch khả dụng</a><form method="post" action="<?= e(url('/host/listings/'.$listing['id'].'/delete')) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger" data-confirm="Xóa mềm tin này? Lịch sử booking sẽ được giữ.">Xóa tin</button></form><?php if($listing['moderation_status']==='approved'&&$listing['is_visible']): ?><a class="btn btn-sm btn-ghost" href="<?= e(url('/listings/'.$listing['id'])) ?>">Xem tin</a><?php endif; ?></div></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></section>
<section class="surface-card mt-4"><h2>Yêu cầu đặt chỗ</h2><?php if(!$bookings): ?><div class="empty-state"><h3>Chưa có yêu cầu đặt chỗ</h3><p>Booking mới sẽ xuất hiện tại đây.</p></div><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Khách</th><th>Chỗ ở</th><th>Ngày</th><th>Tổng</th><th>Trạng thái / hành động</th></tr></thead><tbody>
<?php foreach($bookings as $booking): ?><tr><td><?= e($booking['guest_name']) ?><br><small><?= in_array($booking['status'],['confirmed','completed'],true)?e($booking['guest_phone']):'Liên hệ sau xác nhận' ?></small></td><td><a href="<?= e(url('/bookings/'.$booking['id'])) ?>"><?= e($booking['title']) ?> · #<?= (int)$booking['id'] ?></a><br><?= (int)$booking['guest_count'] ?> khách</td><td><?= e($booking['check_in']) ?> → <?= e($booking['check_out']) ?></td><td><?= number_format((float)$booking['total_amount'],0,',','.') ?>đ</td><td><span class="status status-<?= e($booking['status']) ?>"><?= e($booking['status']) ?></span><?php if($booking['status']==='pending'): ?><div class="action-row"><form method="post" action="<?= e(url('/host/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="confirmed"><button class="btn btn-sm btn-primary">Chấp nhận</button></form><form method="post" action="<?= e(url('/host/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="rejected"><button class="btn btn-sm btn-outline-danger">Từ chối</button></form></div><?php elseif($booking['status']==='confirmed'&&$booking['check_out']<=date('Y-m-d')): ?><form method="post" action="<?= e(url('/host/bookings/'.$booking['id'].'/transition')) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="completed"><button class="btn btn-sm btn-primary">Hoàn thành</button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></section>
<section class="surface-card mt-4"><h2>Doanh thu theo tháng</h2><p class="text-muted">Chỉ đơn hoàn thành, nhóm theo tháng trả phòng; gồm phụ phí.</p><?php if(!$monthlyRevenue): ?><p>Chưa có đơn hoàn thành.</p><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Tháng</th><th>Đơn hoàn thành</th><th>Doanh thu</th></tr></thead><tbody><?php foreach($monthlyRevenue as $month): ?><tr><td><?= e($month['revenue_month']) ?></td><td><?= (int)$month['completed_count'] ?></td><td><?= number_format((float)$month['revenue'],0,',','.') ?>đ</td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></div></section>
