<?php
$isEdit = $listing !== null;
$oldInput = $old ?? [];
$listing = array_merge($listing ?? [], $oldInput);
$selectedAmenities = $oldInput['amenities'] ?? $selectedAmenities;
?>
<section class="page-section"><div class="container narrow">
<div class="section-title"><div><p class="eyebrow">HOST</p><h1><?= $isEdit ? 'Chỉnh sửa chỗ ở' : 'Đăng chỗ ở mới' ?></h1><p>Sau khi lưu, tin sẽ được Admin duyệt trước khi xuất hiện công khai.</p></div></div>
<form class="surface-card" method="post" enctype="multipart/form-data" action="<?= e(url($isEdit ? '/host/listings/'.$listing['id'] : '/host/listings')) ?>"><?= csrf_field() ?>
<div class="form-group"><label for="title">Tên chỗ ở</label><input class="form-control" id="title" name="title" value="<?= e($listing['title'] ?? '') ?>" required></div>
<div class="form-row"><div class="form-group col-md-6"><label for="property_type_id">Loại chỗ ở</label><select class="form-control" id="property_type_id" name="property_type_id"><?php foreach($types as $type): ?><option value="<?= (int)$type['id'] ?>" <?= (int)($listing['property_type_id']??0)===(int)$type['id']?'selected':'' ?>><?= e($type['name']) ?></option><?php endforeach; ?></select></div><div class="form-group col-md-6"><label for="cancellation_policy_id">Chính sách hủy</label><select class="form-control" id="cancellation_policy_id" name="cancellation_policy_id"><?php foreach($policies as $policy): ?><option value="<?= (int)$policy['id'] ?>" <?= (int)($listing['cancellation_policy_id']??0)===(int)$policy['id']?'selected':'' ?>><?= e($policy['name']) ?></option><?php endforeach; ?></select></div></div>
<div class="form-row"><div class="form-group col-md-8"><label for="address">Địa chỉ</label><input class="form-control" id="address" name="address" value="<?= e($listing['address']??'') ?>" required></div><div class="form-group col-md-4"><label for="city">Thành phố</label><input class="form-control" id="city" name="city" value="<?= e($listing['city']??'') ?>" required></div></div>
<div class="form-group"><label for="description">Mô tả</label><textarea class="form-control" id="description" name="description" rows="5" required><?= e($listing['description']??'') ?></textarea></div>
<div class="form-row"><div class="form-group col-md-4"><label for="nightly_price">Giá / đêm</label><input id="nightly_price" class="form-control" type="number" min="1" name="nightly_price" value="<?= e($listing['nightly_price']??'') ?>" required></div><div class="form-group col-md-4"><label for="cleaning_fee">Phụ phí vệ sinh</label><input id="cleaning_fee" class="form-control" type="number" min="0" name="cleaning_fee" value="<?= e($listing['cleaning_fee']??0) ?>"></div><div class="form-group col-md-4"><label for="max_guests">Số khách tối đa</label><input id="max_guests" class="form-control" type="number" min="1" name="max_guests" value="<?= e($listing['max_guests']??1) ?>" required></div></div>
<div class="form-row"><div class="form-group col-4"><label for="room_count">Số phòng</label><input id="room_count" class="form-control" type="number" min="1" name="room_count" value="<?= e($listing['room_count']??1) ?>"></div><div class="form-group col-4"><label for="bedroom_count">Phòng ngủ</label><input id="bedroom_count" class="form-control" type="number" min="1" name="bedroom_count" value="<?= e($listing['bedroom_count']??1) ?>"></div><div class="form-group col-4"><label for="bed_count">Giường</label><input id="bed_count" class="form-control" type="number" min="1" name="bed_count" value="<?= e($listing['bed_count']??1) ?>"></div></div>
<div class="form-row"><div class="form-group col-md-6"><label for="check_in_time">Giờ nhận phòng</label><input id="check_in_time" class="form-control" type="time" name="check_in_time" value="<?= e(substr($listing['check_in_time']??'14:00',0,5)) ?>"></div><div class="form-group col-md-6"><label for="check_out_time">Giờ trả phòng</label><input id="check_out_time" class="form-control" type="time" name="check_out_time" value="<?= e(substr($listing['check_out_time']??'11:00',0,5)) ?>"></div></div>
<fieldset class="form-group"><legend>Tiện nghi</legend><div class="check-grid"><?php foreach($amenities as $amenity): ?><label><input type="checkbox" name="amenities[]" value="<?= (int)$amenity['id'] ?>" <?= in_array((int)$amenity['id'],$selectedAmenities??[],true)?'checked':'' ?>> <?= e($amenity['name']) ?></label><?php endforeach; ?></div></fieldset>
<fieldset class="form-group"><legend>Nội quy</legend><div class="check-grid"><label><input type="checkbox" name="allows_smoking" <?= !empty($listing['allows_smoking'])?'checked':'' ?>> Cho phép hút thuốc</label><label><input type="checkbox" name="allows_pets" <?= !empty($listing['allows_pets'])?'checked':'' ?>> Cho phép thú cưng</label><label><input type="checkbox" name="allows_parties" <?= !empty($listing['allows_parties'])?'checked':'' ?>> Cho phép tiệc</label></div></fieldset>
<div class="form-group"><label for="photo">Thêm ảnh (JPG, PNG, WebP)</label><input class="form-control-file" id="photo" type="file" name="photo" accept="image/jpeg,image/png,image/webp"></div>
<button class="btn btn-primary" type="submit">Lưu và gửi duyệt</button> <a class="btn btn-ghost" href="<?= e(url('/host')) ?>">Hủy</a></form>
</div></section>
<?php if($isEdit): ?>
<section class="page-section pt-0"><div class="container narrow"><form class="surface-card" method="post" action="<?= e(url('/host/listings/'.$listing['id'].'/photos')) ?>"><?= csrf_field() ?>
<h2>Quản lý ảnh hiện có</h2><p>Đổi thứ tự (số nhỏ hiển thị trước) hoặc chọn ảnh cần gỡ. Tin được duyệt lại sau khi thay đổi ảnh; file gốc không bị xóa.</p>
<?php if(!$photos): ?><p class="text-muted">Chưa có ảnh. Dùng mục “Thêm ảnh” ở trên.</p><?php else: ?><div class="row">
<?php foreach($photos as $index=>$photo): ?><div class="col-sm-6 mb-3"><img class="photo-thumbnail" src="<?= e(image_url($photo['image_url'])) ?>" alt="<?= e($photo['alt_text']) ?>">
<label for="position-<?= (int)$photo['id'] ?>">Thứ tự ảnh <?= $index+1 ?></label><input class="form-control mb-2" id="position-<?= (int)$photo['id'] ?>" type="number" min="1" max="100" name="positions[<?= (int)$photo['id'] ?>]" value="<?= $index+1 ?>" required>
<label><input type="checkbox" name="remove[]" value="<?= (int)$photo['id'] ?>"> Gỡ ảnh này khỏi tin</label></div><?php endforeach; ?></div><button class="btn btn-outline-primary" data-confirm="Lưu thứ tự/gỡ ảnh đã chọn và gửi tin duyệt lại?">Lưu quản lý ảnh</button><?php endif; ?>
</form></div></section><?php endif; ?>
