<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Models\AdminRepository;
use App\Models\Booking;
use App\Models\User;
use App\Services\BookingService;
use Core\Controller;
use Core\Csrf;
use Core\Session;
final class AdminController extends Controller
{
    public function dashboard(): void {$this->requireRole('admin');$repo=new AdminRepository();$this->render('admin/dashboard',['title'=>'Quản trị Home2Home','stats'=>$repo->stats(),'users'=>(new User())->all((string)($_GET['q']??'')),'listings'=>$repo->listings(),'bookings'=>(new Booking())->all()]);}
    public function userStatus(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');$status=(string)($_POST['status']??'');if((int)$id===(int)$admin['id']){Session::flash('error','Không thể tự khóa tài khoản đang đăng nhập.');$this->redirect('/admin');}if(in_array($status,['active','suspended'],true)){(new User())->setStatus((int)$id,$status);(new AdminRepository())->audit((int)$admin['id'],'set_user_status','user',(int)$id,$status);Session::flash('success','Đã cập nhật tài khoản.');}$this->redirect('/admin');}
    public function userRoles(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');if((int)$id===(int)$admin['id']){Session::flash('error','Không thể tự thay đổi vai trò Admin đang đăng nhập.');$this->redirect('/admin');}(new User())->replaceRoles((int)$id,$_POST['roles']??[]);(new AdminRepository())->audit((int)$admin['id'],'set_user_roles','user',(int)$id,implode(',',$_POST['roles']??[]));Session::flash('success','Đã cập nhật vai trò.');$this->redirect('/admin');}
    public function userCreate(): never {Csrf::ensure();$admin=$this->requireRole('admin');$data=['full_name'=>trim((string)($_POST['full_name']??'')),'email'=>trim((string)($_POST['email']??'')),'phone'=>trim((string)($_POST['phone']??'')),'password'=>(string)($_POST['password']??'')];if($data['full_name']===''||!filter_var($data['email'],FILTER_VALIDATE_EMAIL)||strlen($data['password'])<8){Session::flash('error','Thông tin tài khoản mới không hợp lệ.');$this->redirect('/admin');}try{$newId=(new User())->adminCreate($data,$_POST['roles']??['guest']);(new AdminRepository())->audit((int)$admin['id'],'create_user','user',$newId,$data['email']);Session::flash('success','Đã tạo tài khoản.');}catch(\Throwable $e){Session::flash('error','Không thể tạo tài khoản: '.$e->getMessage());}$this->redirect('/admin');}
    public function userEdit(string $id): void {$this->requireRole('admin');$user=(new User())->findForAdmin((int)$id);if(!$user){http_response_code(404);$this->render('errors/404',['title'=>'Không tìm thấy tài khoản']);return;}$this->render('admin/user-edit',['title'=>'Sửa tài khoản','managedUser'=>$user]);}
    public function userUpdate(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');$data=['full_name'=>trim((string)($_POST['full_name']??'')),'email'=>trim((string)($_POST['email']??'')),'phone'=>trim((string)($_POST['phone']??'')),'password'=>(string)($_POST['password']??'')];if($data['full_name']===''||!filter_var($data['email'],FILTER_VALIDATE_EMAIL)){Session::flash('error','Thông tin cập nhật không hợp lệ.');$this->redirect('/admin');}(new User())->adminUpdate((int)$id,$data);(new User())->replaceRoles((int)$id,$_POST['roles']??['guest']);(new AdminRepository())->audit((int)$admin['id'],'update_user','user',(int)$id,$data['email']);Session::flash('success','Đã cập nhật tài khoản.');$this->redirect('/admin');}
    public function userDelete(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');if((int)$id===(int)$admin['id']){Session::flash('error','Không thể tự xóa tài khoản đang đăng nhập.');$this->redirect('/admin');}(new User())->softDelete((int)$id);(new AdminRepository())->audit((int)$admin['id'],'delete_user','user',(int)$id,'Soft delete');Session::flash('success','Đã xóa mềm tài khoản.');$this->redirect('/admin');}
    public function moderate(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');$action=(string)($_POST['action']??'');$note=trim((string)($_POST['note']??''));if(!in_array($action,['approved','rejected'],true)||($action==='rejected'&&$note==='')){Session::flash('error','Từ chối bài đăng phải có lý do.');$this->redirect('/admin');}(new AdminRepository())->moderate((int)$id,(int)$admin['id'],$action,$note);Session::flash('success','Đã cập nhật kiểm duyệt bài đăng.');$this->redirect('/admin');}
    public function listingEdit(string $id): void {$this->requireRole('admin');$listing=(new AdminRepository())->findListing((int)$id);if(!$listing){http_response_code(404);$this->render('errors/404',['title'=>'Không tìm thấy chỗ ở']);return;}$this->render('admin/listing-edit',['title'=>'Sửa chỗ ở','listing'=>$listing]);}
    public function listingUpdate(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');$data=['title'=>trim((string)($_POST['title']??'')),'address'=>trim((string)($_POST['address']??'')),'city'=>trim((string)($_POST['city']??'')),'description'=>trim((string)($_POST['description']??'')),'nightly_price'=>(float)($_POST['nightly_price']??0),'cleaning_fee'=>(float)($_POST['cleaning_fee']??0),'max_guests'=>(int)($_POST['max_guests']??0)];if($data['title']===''||$data['nightly_price']<=0||$data['max_guests']<1){Session::flash('error','Thông tin listing không hợp lệ.');$this->redirect('/admin/listings/'.$id.'/edit');}(new AdminRepository())->updateListing((int)$id,(int)$admin['id'],$data);Session::flash('success','Đã cập nhật listing.');$this->redirect('/admin');}
    public function listingVisibility(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');(new AdminRepository())->setListingVisibility((int)$id,(int)$admin['id'],!empty($_POST['visible']));Session::flash('success','Đã cập nhật hiển thị listing.');$this->redirect('/admin');}
    public function listingDelete(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');(new AdminRepository())->softDeleteListing((int)$id,(int)$admin['id']);Session::flash('success','Đã gỡ listing (soft delete).');$this->redirect('/admin');}
    public function bookingTransition(string $id): never {Csrf::ensure();$admin=$this->requireRole('admin');try{(new BookingService())->adminTransition((int)$id,(int)$admin['id'],(string)($_POST['status']??''));(new AdminRepository())->audit((int)$admin['id'],'transition_booking','booking',(int)$id,(string)($_POST['status']??''));Session::flash('success','Đã cập nhật booking.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}$this->redirect('/admin');}
}

