<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Models\Booking;
use App\Models\HostRepository;
use App\Models\Listing;
use App\Services\BookingService;
use App\Services\UploadService;
use Core\Controller;
use Core\Csrf;
use Core\Session;
final class HostController extends Controller
{
    public function dashboard(): void {$u=$this->requireRole('host');$this->render('host/dashboard',['title'=>'Không gian Host','stats'=>(new HostRepository())->stats((int)$u['id']),'listings'=>(new Listing())->hostListings((int)$u['id']),'bookings'=>(new Booking())->forHost((int)$u['id'])]);}
    public function createForm(): void {$this->requireRole('host');$m=new Listing();$this->render('host/listing-form',['title'=>'Đăng chỗ ở','listing'=>null,'types'=>$m->types(),'policies'=>$m->policies(),'amenities'=>$m->allAmenities(),'selectedAmenities'=>[]]);}
    public function editForm(string $id): void {$u=$this->requireRole('host');$m=new Listing();$listing=$m->findOwned((int)$id,(int)$u['id']);if(!$listing){http_response_code(404);$this->render('errors/404',['title'=>'Không tìm thấy chỗ ở']);return;}$this->render('host/listing-form',['title'=>'Chỉnh sửa chỗ ở','listing'=>$listing,'types'=>$m->types(),'policies'=>$m->policies(),'amenities'=>$m->allAmenities(),'selectedAmenities'=>$m->amenityIds((int)$id)]);}
    public function availabilityPage(string $id): void {$u=$this->requireRole('host');$m=new Listing();$listing=$m->findOwned((int)$id,(int)$u['id']);if(!$listing){http_response_code(404);$this->render('errors/404',['title'=>'Không tìm thấy chỗ ở']);return;}$this->render('host/availability',['title'=>'Lịch khả dụng','listing'=>$listing,'dates'=>$m->availability((int)$id,(int)$u['id'])]);}
    public function store(): never {Csrf::ensure();$u=$this->requireRole('host');$this->persist(null,(int)$u['id']);}
    public function update(string $id): never {Csrf::ensure();$u=$this->requireRole('host');$this->persist((int)$id,(int)$u['id']);}
    private function persist(?int $id,int $hostId): never {$data=$this->listingInput();$required=['title','address','city','description'];foreach($required as $field){if(trim((string)$data[$field])===''){Session::flash('error','Vui lòng nhập đầy đủ thông tin bắt buộc.');$this->redirect($id?'/host/listings/'.$id.'/edit':'/host/listings/create');}}if((float)$data['nightly_price']<=0||(int)$data['max_guests']<1){Session::flash('error','Giá và sức chứa phải lớn hơn 0.');$this->redirect($id?'/host/listings/'.$id.'/edit':'/host/listings/create');}$m=new Listing();try{if($id){if(!$m->findOwned($id,$hostId)){throw new \DomainException('Không có quyền sửa chỗ ở.');}$m->update($id,$hostId,$data);}else{$id=$m->create($hostId,$data);}$m->setAmenities($id,$_POST['amenities']??[]);$photo=(new UploadService())->image($_FILES['photo']??[],'listing-'.$id);if($photo){$m->addPhoto($id,$photo,$data['title']);}Session::flash('success','Đã lưu chỗ ở và chuyển về trạng thái chờ duyệt.');$this->redirect('/host');}catch(\Throwable $e){Session::flash('error',$e->getMessage());$this->redirect($id?'/host/listings/'.$id.'/edit':'/host/listings/create');}}
    private function listingInput(): array {return ['property_type_id'=>(int)($_POST['property_type_id']??0),'cancellation_policy_id'=>(int)($_POST['cancellation_policy_id']??0),'title'=>trim((string)($_POST['title']??'')),'address'=>trim((string)($_POST['address']??'')),'city'=>trim((string)($_POST['city']??'')),'description'=>trim((string)($_POST['description']??'')),'nightly_price'=>(float)($_POST['nightly_price']??0),'cleaning_fee'=>(float)($_POST['cleaning_fee']??0),'max_guests'=>(int)($_POST['max_guests']??0),'room_count'=>(int)($_POST['room_count']??1),'bedroom_count'=>(int)($_POST['bedroom_count']??1),'bed_count'=>(int)($_POST['bed_count']??1),'check_in_time'=>(string)($_POST['check_in_time']??'14:00'),'check_out_time'=>(string)($_POST['check_out_time']??'11:00'),'allows_smoking'=>isset($_POST['allows_smoking']),'allows_pets'=>isset($_POST['allows_pets']),'allows_parties'=>isset($_POST['allows_parties'])];}
    public function visibility(string $id): never {Csrf::ensure();$u=$this->requireRole('host');(new Listing())->setVisible((int)$id,(int)$u['id'],!empty($_POST['visible']));Session::flash('success','Đã cập nhật hiển thị.');$this->redirect('/host');}
    public function availability(string $id): never {Csrf::ensure();$u=$this->requireRole('host');$date=(string)($_POST['date']??'');$valid=\DateTimeImmutable::createFromFormat('!Y-m-d',$date);$message='Ngày không hợp lệ.';$ok=$valid&&$valid->format('Y-m-d')===$date&&$valid>=new \DateTimeImmutable('today');if($ok){$ok=(new Listing())->setAvailability((int)$id,(int)$u['id'],$date,!empty($_POST['open']),(string)($_POST['reason']??''));$message=$ok?'Đã cập nhật lịch.':'Không thể chặn ngày đã có booking xác nhận.';}if(str_contains((string)($_SERVER['HTTP_ACCEPT']??''),'application/json')){$this->json($ok,$message,null,[],$ok?200:422);}Session::flash($ok?'success':'error',$message);$this->redirect('/host/listings/'.$id.'/availability');}
    public function transition(string $id): never {Csrf::ensure();$u=$this->requireRole('host');try{(new BookingService())->hostTransition((int)$id,(int)$u['id'],(string)($_POST['status']??''));Session::flash('success','Đã cập nhật booking.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}$this->redirect('/host');}
}

